idemeum/teleport

lib/publisher/sqsapppublisher.go

- Standard sqs queue does not allow the messageDeduplicationId to be sent as
part of sendMessage request its only applies to FIFO queue
- We are using the standard sqs queue, as the at least once delivery is good enough for us to process the changes.

IDEM-1888: Part3 fix the sqs queue send message failure

---

lib/config/configuration.go
lib/config/fileconf.go
lib/publisher/auditpublisher.go
lib/publisher/auditpublisher_test.go
lib/publisher/sqsauditpublisher.go
lib/service/cfg.go
lib/service/service.go

1. Added AuditPublisher which will publish the required events to
idemeum app management
2. Added configuration enable the audit publishing
3. Added AuditMessagePublisher which is responsible to publish the audit
message to destination
4. Added unit tests

IDEM-1930: Added AuditPublisher to publish audit events

---

lib/auth/auth.go
lib/auth/bot.go
lib/auth/db.go
lib/auth/desktop.go
lib/auth/kube.go
lib/auth/sessions.go
lib/kube/proxy/auth.go
lib/kube/utils/utils.go
lib/reversetunnel/localsite.go
lib/service/desktop.go
lib/service/kubernetes.go
lib/web/app/redirect.go

- Changed the error message to show as idemeum rather than
teleport keyword to avoid confusion for end user

IDEM-1948: Changed error message branding to idemeum

---

Makefile
build.assets/Dockerfile
build.assets/Makefile
examples/systemd/README.md
examples/systemd/idemeum.service
examples/systemd/teleport.service
support/cloud-build.sh
support/prod-cloud-build.sh
support/stg-cloud-build.sh

- Fixed the build problem using the ubuntu
by removing the libudev-dev dependency which has been
removed in the teleport repo as well.
- Build and publish binaries to s3

IDEM-1976: Build and publish binaries to s3

---

lib/auth/auth.go
lib/auth/auth_with_roles.go
lib/auth/helpers.go
lib/auth/init.go
lib/config/configuration.go
lib/config/fileconf.go
lib/inventory/controller.go
lib/publisher/apppublisher.go
lib/publisher/sqsapppublisher.go
lib/service/service.go
lib/services/local/presence.go
lib/srv/heartbeat.go
lib/srv/heartbeatv2.go

- Teleport announce proxy, ssh nodes to auth server using the heartbeat announcemechanism.
- Changed the presence service code to publish the event only if the node is inserted in the auth service storage. Every service maintains its own local DB where the record is inserted, its done carefully not to publish events for those updates.
- Added logs to debug issue in case event is published or not

IDEM-1999: Publish the event when ssh node is added to auth server

---

lib/auth/auth.go
lib/inventory/controller.go
lib/publisher/apppublisher.go
lib/publisher/remoteaccessappwatcher.go
lib/publisher/sqsapppublisher.go
lib/services/local/presence.go

- Teleport monitors the database changes using the Events framework
- Plugged-in the remote access watcher to monitor the deleted resources to send the notification to app management
- Added default delay of 30s for publishing message to app management as the teleport in-memory cache is eventually consistent it takes time to reflect the changes

IDEM-2012: Send notification when the resource is deleted in db

---

lib/auth/init.go
lib/config/configuration.go
lib/config/fileconf.go
lib/service/cfg.go
lib/service/service.go
lib/services/idemeumpresets.go
lib/services/idemeumpresets_test.go

- added presets for roles admin and user
- added presets for saml connector configuration based on tenantUrl
- added knob to enable/dsiable the applying the idemeum presets during startup

IDEM-2034: Use presets to configure the remote access server

---

lib/web/apiserver.go

- when user is trying to access the teleport / or /web/login redirect it to idemeum user portal

IDEM-1892: Part2 redirect user to idemeum user portal

---

examples/idemeum-readme.md
examples/systemd/agent-setup

Sample installation output
```
root@ip-10-2-48-180:/var/snap/amazon-ssm-agent/5656/idemeum# bash agent-setup
agent-setup: line 1: !/bin/bash: No such file or directory
[Error] Agent name not provided.
Enter valid agent name.
Only alphanumeric charaters allowed & lenght 3-20.
[Input Agent Name] : fookesh1
[Error] Agent config file not provided.
Enter config file path.
[Input Agent Config] : ../fookesh.yaml
*****************  Installing Agent *******************
Agent name : fookesh1
[sudo] Writing agent service : /etc/systemd/system/fookesh1.service
[sudo] Copying agent config : ../fookesh.yaml -> /etc/fookesh1.yaml
[info] Using   data_dir: "/var/lib/idemeum-43d8b404-d29b-468c-8bd4-8cc84b0ba9df"
[sudo] Reloading systemctl daemons.
[sudo] Enabling service : fookesh1
Created symlink …
```

IDEM-2055: fix agent config files

---

examples/aws/cloudformation/idemeum.yaml

Aș per the teleport documentation, only the proxy service should be available to the outside world.
Make the auth service only available from the proxy service nodes of the tenant teleport cluster.

IDEM-2165: only proxy services should have access to the auth service

---

examples/aws/cloudformation/idemeum.yaml

This is a temporary fix, in my opinion.
Problem:
Every time we create the teleport stack for a tenant, the resources that are created will be monitored by Vanta. Then it will complain about the following:
EC2 instances (proxy & auth) does not have the server CPU monitored
EC2 instance exposes public ports
DynamoDb Tables for Main, Events & Locks does not have the Read & Write capacity monitored.
Discussed with Vanta and there is no way to pull in the resources and disable only certain tests (for example the public ports). So we will use the VantaNoAlert to not create the alarms for this resource.
In my opinion this is a temporary fix. We should be creating the alarms for Read/Write capacity for the tables and server CPU for the EC2 instances even when the customer is in trial mode.
Then …

IDEM-2124: Ignore some teleport resources so we won't have tests failing in Vanta

---

lib/services/idemeumpresets.go
lib/services/idemeumpresets_test.go

- Teleport generates the remote access server url from the given idemeum tenant url
- if idemeum tenant is example.idemeum.in then the remote server url will be : example.remote.idemeum.in
- also handles for domains like example.idemeum.co.jp -> example.remote.idemeum.co.jp

IDEM-2253: Fixed the saml connector url generation

---

api/types/desktop.go
lib/auth/auth_with_roles.go
lib/publisher/auditpublisher.go
lib/publisher/remoteaccessappwatcher.go

- Enable audit for windows desktop session start and end
- Entitle the user based on the windows hostId
- Send notification to user only for the windows host add/update or remove

IDEM-2212: Windows desktop notification

---

lib/srv/desktop/windows_server.go
lib/srv/desktop/windows_server_test.go

For windowsdesktop service the user DN are setup using the CN=Teleport, CN=.. we would like to change the branding to CN=Idemeum,CN=..

IDEM-2264: Rename the DN for windows to idemeum

---

lib/config/configuration.go
lib/config/fileconf.go

-Enhanced the windows ldap config to support the ldap ca cert as pem format i.e. example
ldap:
...
ldap_ca_cert: |
-----BEGIN CERTIFICATE-----
*certificate data*
-----END CERTIFICATE-----

IDEM-2261: Allow LDAP pem cert as inline configuration

---

assets/aws/files/bin/teleport-generate-config
examples/aws/cloudformation/idemeum.yaml
lib/auth/auth.go
lib/auth/init.go
lib/auth/init_test.go
lib/auth/trustedcluster_test.go
lib/config/configuration.go
lib/config/fileconf.go
lib/encryption/encryptionservice.go
lib/encryption/itemencrypter.go
lib/service/cfg.go
lib/service/service.go
lib/services/local/resource_test.go
lib/services/local/trust.go

1.We have added encryption service which will provide the encryption
for the sensitive data i.e cert authority CA data
2. Added KMS based encryption and test encryption for test purpose
3. Added the encryption support for CertAuthority database item when its saved to DB or read from DB to minimize the changes as the CertAuthority object is used across multiple places
4. Added logic to encrypt the existing CertAuthority value as JSON to indicate whether the data is encrypted or not, using this during the DB load we will decide to decrypt the data or not.

IDEM-2704: Encrypt cert authority using kms

---

examples/aws/cloudformation/idemeum.yaml

Fixed typo in the idemeum.yaml file
While testing the logout feature, I've noticed that I could not update the cloud formation stack due to this issue. 
Sending it separate review to make it simpler.

Fix typo in the idemeum.yaml file

---

lib/auth/apiserver.go
lib/auth/auth_with_roles.go
lib/auth/auth_with_roles_test.go
lib/auth/clt.go
lib/auth/idemeum.go
lib/encryption/encryptionservice.go
lib/web/apiserver.go
lib/web/apiserver_test.go
lib/web/sessions.go

When logging out of idemeum we are posting a message to teleport to logout user from teleport.
This PR: https://github.com/idemeum/appmanagement/pull/1595 has the app management changes. AppManagement will post as message with userId, deviceId and tokenId to /webapi//idp/logout 
This api will get the user and will try to get all the user's sessions by making a call to Auth Proxy new endpoint /user/sessions
This API's implementation is rudimentary as of now: it gets all the web sessions and then it filters out only the sessions for this user and returns them. 
Now on the Proxy service we have the web sessions and we just call invalidate on all those sessions. 
If you want to test you can onboard to localgeorge6.idemeumlab.com (for Ashok and Kamlesh I have used your idemeum email and for …

IDEM-1799: logging out of idemeum logs out from teleport

---

assets/aws/files/bin/teleport-generate-config

- We have hit the plainText limit where as kms only encrypts upto 4k bytes, while the cert authority object is more than 4k.
- Disabling the kms encryption until we found solution to this issue

IDEM-2704: Part3 disable the kms encryption

---

tool/tsh/help.go
tool/tsh/tsh.go

There are a lot of commands that can be executed using the tsh script. 
My suggestion is to suppress most of them and only add them as the customers requests for them. These are the commands allowed by the tsh script:
Commands:
help           Show help.
version        Print the version of your tsh binary
ssh            Run shell or execute a command on a remote SSH node
aws            Access AWS API.
apps ls        List available applications.
apps login     Retrieve short-lived certificate for an app.
apps logout    Remove app certificate.
apps config    Print app connection information.
proxy ssh      Start local TLS proxy for ssh connections when using Teleport in single-port mode
proxy db       Start local TLS proxy for database connections when using Teleport in single-port mode …

IDEM-2863: ignore commands that we don't want to expose on the tsh command script

---

tool/tsh/help.go
tool/tsh/tsh.go

Comment out the --proxy flag at the tsh level and added the tenant-url flag for the login command.
georgeoprean@george build % ./tsh help login
usage: tsh login [<flags>]
Log in to a Remote Access server and retrieve the session certificate
Flags:
-l, --login                    Remote host login
--ttl                      Minutes to live for a SSH session
-i, --identity                 Identity file
--cert-format              SSH certificate format
--insecure                 Do not verify server's certificate and host name. Use only in test environments
--skip-version-check       Skip version checking between server and client.
-d, --debug                    Verbose logging to stdout
-k, --add-keys-to-agent        Controls how keys are handled. Valid values are [auto no yes only]. …

IDEM-2864: added a tenant-url to the login command

---

api/profile/profile.go
lib/client/api.go
tool/tsh/tsh.go

After the loging completes (and it will be the same output for the status command) we only need to display a handful of information to the user. So ignored all the other messages that were displayed and kept it to the minimum. 
I have added the Idemeum tenant url since the proxy cluster did not had any meaning to the user. 
Here is an example of how it will look after a login message
**georgeoprean@george build % ./tsh login --tenant-url=georgelocal6.idemeumlab.com
If browser window does not open automatically, open it by clicking on the link:
http://127.0.0.1:64926/1ff6386b-8358-4fbe-b9bb-25c06ee13def
> Idemeum Tenant:     georgelocal6.idemeumlab.com
Logged in as:       goprean@gmail.com
Valid until:        2023-04-21 23:51:31 +0300 EEST [valid for 6h19m0s]**

IDEM-2865: part2 - only display a handful of info after the login completes

---

tool/tsh/tsh.go

The login command has an option to pass a ttl (in minutes).
If no ttl is passed then it will default to 12 hours (transformed in minutes). 
To prevent the certificate from being stolen, limit the duration of the cert when it is issued to 12 hours. If no ttl is passed in then the cert will only be valid for 60 mins. 
If the user already has a session with idemeum or if the session for idemeum is set to 8 hours and the user asks for a cert t be valid for 10 hours, then the cert issue will only be valid for 8 hours. 
The ssh cert will never be expire after the idemeum session expired. For example let's assume that a tenant has the idemeum session set for 8 hours. And a user has been logged in 7h:30 mins ago. 
When this user requests for a ssh cert (by executing the ./tsh login command) the …

IDEM-2874: limit the ssh certificate duration to 1h if no ttl is passed

---

Makefile
api/profile/profile.go
lib/srv/reexec.go
tool/tsh/tsh.go
tool/tsh/tshconfig_test.go

Rename the script from tsh to ish. 
When you need to build the ish script locally from teleport git repo you now can run: make build/ish

IDEM-2877: build the script as ish instead of tsh

---

api/utils/keypaths/keypaths.go

When testing the ish script on Windows I was running into errors. 
the ish login command will contain in the response a bunch of certificates/private/public keys and ssh certs. These are saved on disk using the username as a filename prefix. 
In idemeum the username has the "did:dvmi:" prefix. The problem on windows is that the filenames cannot contain ":" (colon) character. 
Solution:
when trying to get the file path for the certs/keys/ replace the "did:dvmi:" prefix with "idemeum-" prefix. 
It is nicely contained din the key paths.go class since that's where all the key paths / filenames are created

IDEM-2908: escape username when saving the cert files

---

assets/aws/files/bin/teleport-generate-config
assets/aws/files/install.sh

In order to allow just one port to handle multiple application protocols (http, ssh, sql, etc) we need to set the proxy_listener_mode attribute to multiplex on the auth_service.
Also explicitly set v2 as the configuration version file.

IDEM-2953: added v2 of the config file and set the proxy listener mode to multiplex

---

assets/aws/files/bin/teleport-generate-config
examples/aws/cloudformation/idemeum.yaml

All the teleport deployments will use TLS routing. So only port 443 is exposed on the proxy server to the outside world. 
Remove port 3023 from the security group on the proxy server. 
Also set the ssh_public_addr port to 443 instead of 3023

IDEM-2955: Do not expose port 3023 on the security group
